### ISSUE TITLE
indent size is forced to 1

### ISSUE THREAD

**Issue by yuki-takei** [sheehan/grails-console#60]
How to reproduce?
--------------------

* Grails 3.2.4
* grails-console:2.0.8
* application.yml
    ```
    grails:
        plugin:
            console:
                indentUnit: 4
    ```
* Firefox 52.0.1

1. goto console
2. hit tab key

What is happened?
--------------------

1. indented by 1 space

What is the expected behavior?
---------------------------------

1. indented by 4 spaces

Why does this happen?
-------------------------

Maybe because of the type of `indentUnit` is boolean. Similarly, the type of `tabSize` is boolean.

https://github.com/sheehan/grails-console/blob/master/grails3/plugin/src/main/groovy/org/grails/plugins/console/ConsoleConfig.groovy#L11
